// vue/pages/[[dashboard]]/cours/[subject]/[course]/_chapters.vue
<script setup lang="ts">
import File from "~/components/icons/File.vue";
import {ChapterType, CourseType} from "~/composables/type";

const route = useRoute()
const {chapters, course} = defineProps<{
  chapters?: ChapterType[],
  course?: CourseType
}>()
const slug = route.params.chapter
</script>
<template>
  <div class="" id="accordionCurriculum">
    <div class="overflow-hidden card rounded mb-6">
      <div v-for="chp in chapters" class="collapse show">
        <NuxtLink :href="`/cours/${course?.subject?.slug}/${course?.slug}/${chp.slug}`" class="border-bottom px-2 border-color-20 py-3 min-height-70 d-md-flex align-items-center text-black">
          <div class="d-flex align-items-center me-auto mb-4 mb-md-0">
            <div class="text-secondary d-flex">
              <File :width="30" :height="30"/>
            </div>
            <div class="ms-4">
              {{ (slug === chp.slug) ? chp.title.toUpperCase() : chp.title }}
            </div>
          </div>
        </NuxtLink>
      </div>
    </div>
  </div>
</template>

// client/src/routes/(dashboard)/cours/[subject]/[course]/Chapters.svelte
<script lang="ts">
    import type {ChapterType} from "$lib/type";
    import {fly} from "svelte/transition";
    import Course from "../../../admin/courses/[courseUid]/Course.svelte";
    import {page} from "$app/stores";
    import RIghtArrow from "$lib/components/icons/RIghtArrow.svelte";

    export let chapters: ChapterType[] = []
    export let course: Course
    const slug = $page.params.chapter
</script>

{#each chapters as chp,index(chp.id)}
    <div transition:fly="{{x:-100, duration:400}}" class="border-bottom border-color-10 py-2">
        <h3 class="text-muted">
            <RIghtArrow/>
            <a href={`/cours/${course?.subject?.slug}/${course?.slug}/${chp.slug}`} class:text-black={slug && slug===chp.slug}>{slug && slug === chp.slug ? chp.title.toUpperCase() : chp.title}</a>
        </h3>
    </div>

{/each}
