// vue/pages/[[dashboard]]/admin/classes/index.vue
<script setup lang="ts">
import {ClasseType} from "~/composables/type";
import {ClasseStore} from "~/composables/store";
import ClasseList from "~/pages/[[dashboard]]/admin/classes/ClasseList.vue";
import ClasseForm from "~/pages/[[dashboard]]/admin/classes/ClasseForm.vue";
import {activeMenu} from "~/utils/layout";

const classes = ref<ClasseType[]>([])
const currentClasse = ref<ClasseType>({name: '', id: 0, description: '', uid: ''})

onMounted(() => activeMenu("#classes_menu"))
const getClasses = async () => getRequest('/classes').then(response => ClasseStore.setClasses(response.data))
const setCurrentClasse = (data: ClasseType) => currentClasse.value = data

</script>
<template>
  <Head>
    <Title>I-Cours - Classes</Title>
  </Head>

  <div class="page-header d-print-none">
    <div class="container-xl">
      <div class="row g-2 align-items-center">
        <div class="col">
          <ol aria-label="breadcrumbs" class="breadcrumb breadcrumb-arrows">
            <li class="breadcrumb-item">
              <NuxtLink href="/admin">Tableau de bord</NuxtLink>
            </li>
            <li aria-current="page" class="breadcrumb-item active">
              <h2 class="breadcrumb-current">
                <NuxtLink href="/">Liste classes</NuxtLink>
              </h2>
            </li>
          </ol>
        </div>
      </div>
    </div>
  </div>
  <div class="page-body">
    <div class="container-xl">
      <div class="row g-4">
        <div class="col-md-6">
          <ClasseList @classe-update-request="setCurrentClasse" @classe-updated="getClasses"/>
        </div>
        <div class="col-md-6">
          <ClasseForm :formData="currentClasse" @classe-updated="getClasses"/>
        </div>
      </div>
    </div>
  </div>
</template>

// client/src/routes/[dashboard]/admin/classes/+page.svelte
<script lang="ts">
    import {getRequest} from "$lib/helper/Request";
    import type {ClasseType} from "$lib/type";
    import {onMount} from "svelte";
    import ClasseForm from "./ClasseForm.svelte";
    import ClasseList from "./ClasseList.svelte";
    import {activeMenu} from "$lib/helper/layout";
    import {ClasseStore} from "$lib/store";

    let classes: ClasseType[] = []
    let currentClasse: ClasseType = {name: '', id: 0, description: '', uid: ''};

    onMount(() => {
        activeMenu("#classes_menu")
    })

    async function getClasses() {
        getRequest('/classes').then(response => ClasseStore.set(response.data))
    }

    function setCurrentClasse(event) {
        currentClasse = event.detail.data
    }
</script>

<svelte:head>
    <title>I-Cours - Classes</title>
</svelte:head>

<div class="page-header d-print-none">
    <div class="container-xl">
        <div class="row g-2 align-items-center">
            <div class="col">
                <ol aria-label="breadcrumbs" class="breadcrumb breadcrumb-arrows">
                    <li class="breadcrumb-item"><a href="/dashboard/admin">Tableau de bord</a></li>
                    <li aria-current="page" class="breadcrumb-item active">
                        <h2 class="breadcrumb-current"><a href="/">Liste classes</a></h2>
                    </li>
                </ol>
            </div>
        </div>
    </div>
</div>
<div class="page-body">
    <div class="container-xl">
        <div class="row g-4">
            <div class="col-md-6">
                <ClasseList on:classe-update-request={setCurrentClasse} on:classe-updated={getClasses} classes={$ClasseStore}/>
            </div>
            <div class="col-md-6">
                <ClasseForm formData={currentClasse} on:classe-updated={getClasses}/>
            </div>
        </div>
    </div>
</div>
