// vue/components/layouts/default/chat/Response.vue
<script setup lang="ts">
    const props  = defineProps(['response'])
</script>

<div style="width: 100%;">
    <div class="p-2 bg-light" style="display: flex;">
        <div class="p-2">
            <div class="p-2 text-white border-2" style="background-color: rgb(165, 23, 23);border-radius: .5rem;">{{APP_NAME}}</div>
        </div>
        <div class="p-2" v-html="props.response"/>
    </div>
</div>

// client/src/lib/components/layouts/dashboard/chat/Response.svelte
<script lang="ts">
    export let response = ""
</script>
<div style="width: 100%;">
    <div class="p-2 bg-light" style="display: flex;">
        <div class="p-2">
            <div class="p-2 text-white border-2" style="background-color: rgb(165, 23, 23);border-radius: .5rem;">I-COURS</div>
        </div>
        <div class="p-2">
            <p>{@html response}</p>
        </div>
    </div>
</div>
