// vue/components/layouts/default/ListPlaceholder.vue
<template>
  <ul class="list-group list-group-flush placeholder-glow">
    <li class="list-group-item">
      <div class="row align-items-center">
        <div class="col-auto">
          <div class="avatar avatar-rounded placeholder"></div>
        </div>
        <div class="col-7">
          <div class="placeholder placeholder-xs col-9"></div>
          <div class="placeholder placeholder-xs col-7"></div>
        </div>
        <div class="col-2 ms-auto text-end">
          <div class="placeholder placeholder-xs col-8"></div>
          <div class="placeholder placeholder-xs col-10"></div>
        </div>
      </div>
    </li>
    <li class="list-group-item">
      <div class="row align-items-center">
        <div class="col-auto">
          <div class="avatar avatar-rounded placeholder"></div>
        </div>
        <div class="col-7">
          <div class="placeholder placeholder-xs col-9"></div>
          <div class="placeholder placeholder-xs col-7"></div>
        </div>
        <div class="col-2 ms-auto text-end">
          <div class="placeholder placeholder-xs col-8"></div>
          <div class="placeholder placeholder-xs col-10"></div>
        </div>
      </div>
    </li>
  </ul>
</template>

// client/src/lib/components/layouts/dashboard/ListPlaceholder.svelte
<div class="card">
    <ul class="list-group list-group-flush placeholder-glow">
        <li class="list-group-item">
            <div class="row align-items-center">
                <div class="col-auto">
                    <div class="avatar avatar-rounded placeholder"></div>
                </div>
                <div class="col-7">
                    <div class="placeholder placeholder-xs col-9"></div>
                    <div class="placeholder placeholder-xs col-7"></div>
                </div>
                <div class="col-2 ms-auto text-end">
                    <div class="placeholder placeholder-xs col-8"></div>
                    <div class="placeholder placeholder-xs col-10"></div>
                </div>
            </div>
        </li>
        <li class="list-group-item">
            <div class="row align-items-center">
                <div class="col-auto">
                    <div class="avatar avatar-rounded placeholder"></div>
                </div>
                <div class="col-7">
                    <div class="placeholder placeholder-xs col-9"></div>
                    <div class="placeholder placeholder-xs col-7"></div>
                </div>
                <div class="col-2 ms-auto text-end">
                    <div class="placeholder placeholder-xs col-8"></div>
                    <div class="placeholder placeholder-xs col-10"></div>
                </div>
            </div>
        </li>
    </ul>
</div>
