// client/src/lib/components/layouts/dashboard/AdminMenu.svelte
<li class="nav-item dropdown">
    <a aria-expanded="true" class="nav-link dropdown-toggle show" data-bs-auto-close="false" data-bs-toggle="dropdown" href="#navbar-base" role="button">
          <span class="nav-link-icon d-md-none d-lg-inline-block">
            <svg class="icon" fill="none" height="24" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg"><path d="M0 0h24v24H0z" fill="none" stroke="none"></path><path d="M12 3l8 4.5l0 9l-8 4.5l-8 -4.5l0 -9l8 -4.5"></path><path d="M12 12l8 -4.5"></path><path d="M12 12l0 9"></path><path d="M12 12l-8 -4.5"></path><path d="M16 5.25l-8 4.5"></path></svg>
          </span>
        <span class="nav-link-title">ADMINISTRATION</span>
    </a>
    <div class="dropdown-menu show" data-bs-popper="static" id="admin_menu">
        <div class="dropdown-menu-columns">
            <div class="dropdown-menu-column">
                <a class="dropdown-item" id="courses_menu" href="/dashboard/admin/courses">COURS </a>
                <a class="dropdown-item" id="subjects_menu" href="/dashboard/admin/subjects">MATIÈRES </a>
                <a class="dropdown-item" id="classes_menu" href="/dashboard/admin/classes">CLASSES </a>
            </div>
        </div>
    </div>
</li>

// vue/components/layouts/default/AdminMenu.vue
<template>
  <li class="nav-item dropdown">
    <a aria-expanded="true" class="nav-link dropdown-toggle show" data-bs-auto-close="false" data-bs-toggle="dropdown" href="#navbar-base" role="button">
          <span class="nav-link-icon d-md-none d-lg-inline-block">
            <svg class="icon" fill="none" height="24" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg"><path d="M0 0h24v24H0z" fill="none" stroke="none"></path><path d="M12 3l8 4.5l0 9l-8 4.5l-8 -4.5l0 -9l8 -4.5"></path><path d="M12 12l8 -4.5"></path><path d="M12 12l0 9"></path><path d="M12 12l-8 -4.5"></path><path d="M16 5.25l-8 4.5"></path></svg>
          </span>
      <span class="nav-link-title">Administration</span>
    </a>
    <div class="dropdown-menu show" data-bs-popper="static" id="admin_menu">
      <div class="dropdown-menu-columns">
        <div class="dropdown-menu-column">
          <NuxtLink class="dropdown-item" id="courses_menu" href="/admin/courses">Cours</NuxtLink>
          <NuxtLink class="dropdown-item" id="subjects_menu" href="/admin/subjects">Matières</NuxtLink>
          <NuxtLink class="dropdown-item" id="classes_menu" href="/admin/classes">Classes</NuxtLink>
        </div>
      </div>
    </div>
  </li>
</template>
