// client/src/lib/components/layouts/dashboard/Footer.svelte
<footer class="footer footer-transparent d-print-none">
    <div class="container-xl">
        <div class="row text-center align-items-center flex-row-reverse">
            <div class="col-lg-auto ms-lg-auto">
                <ul class="list-inline list-inline-dots mb-0">
                    <li class="list-inline-item"><a href="/" target="_blank" class="link-secondary">Qui sommes nous?</a></li>
                    <li class="list-inline-item"><a href="/" target="_blank" class="link-secondary">Fonctionnements</a></li>
                    <li class="list-inline-item"><a href="/" target="_blank" class="link-secondary" rel="noopener">Nous contacter</a></li>
                </ul>
            </div>
            <div class="col-12 col-lg-auto mt-3 mt-lg-0">
                <ul class="list-inline list-inline-dots mb-0">
                    <li class="list-inline-item">
                        Copyright © {new Date().getFullYear()}
                        <a href="/" class="link-secondary">I-COURS</a>.
                        Tout droit reservé.
                    </li>
                    <li class="list-inline-item">
                        <a href="https://devkonect.com" class="link-secondary" rel="noopener" target="_blank">
                            DEVKONECT
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>

// vue/components/layouts/default/Footer.vue
<template>
  <footer class="footer footer-transparent d-print-none">
    <div class="container-xl">
      <div class="row text-center align-items-center flex-row-reverse">
        <div class="col-lg-auto ms-lg-auto">
          <ul class="list-inline list-inline-dots mb-0">
            <li class="list-inline-item"><a href="/" target="_blank" class="link-secondary">Qui sommes nous?</a></li>
            <li class="list-inline-item"><a href="/" target="_blank" class="link-secondary">Fonctionnements</a></li>
            <li class="list-inline-item">
              <a href="/" target="_blank" class="link-secondary" rel="noopener">Nous contacter</a></li>
          </ul>
        </div>
        <div class="col-12 col-lg-auto mt-3 mt-lg-0">
          <ul class="list-inline list-inline-dots mb-0">
            <li class="list-inline-item">
              Copyright © {{new Date().getFullYear()}}
              <a href="/" class="link-secondary">I-COURS</a>.
              Tout droit reservé.
            </li>
            <li class="list-inline-item">
              <a href="https://devkonect.com" class="link-secondary" rel="noopener" target="_blank">
                DEVKONECT
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </footer>
</template>
